-- QB-Core Items
-- Copy this into: qb-core/shared/items.lua (QBShared.Items table)
-- Total: 148 items


-- Pistolen
['weapon_pistol'] = {
    name = 'weapon_pistol',
    label = 'Pistol',
    weight = 970,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_pistol.png',
    unique = true,
    useable = false,
    description = 'Pistol'
},
['weapon_pistol_mk2'] = {
    name = 'weapon_pistol_mk2',
    label = 'Pistol Mk2',
    weight = 970,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_pistol_mk2.png',
    unique = true,
    useable = false,
    description = 'Pistol Mk2'
},
['weapon_combatpistol'] = {
    name = 'weapon_combatpistol',
    label = 'Combat Pistol',
    weight = 970,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_combatpistol.png',
    unique = true,
    useable = false,
    description = 'Combat Pistol'
},
['weapon_appistol'] = {
    name = 'weapon_appistol',
    label = 'AP Pistol',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_appistol.png',
    unique = true,
    useable = false,
    description = 'AP Pistol'
},
['weapon_pistol50'] = {
    name = 'weapon_pistol50',
    label = 'Pistol .50',
    weight = 1100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_pistol50.png',
    unique = true,
    useable = false,
    description = 'Pistol .50'
},
['weapon_snspistol'] = {
    name = 'weapon_snspistol',
    label = 'SNS Pistol',
    weight = 465,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_snspistol.png',
    unique = true,
    useable = false,
    description = 'SNS Pistol'
},
['weapon_snspistol_mk2'] = {
    name = 'weapon_snspistol_mk2',
    label = 'SNS Pistol Mk2',
    weight = 465,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_snspistol_mk2.png',
    unique = true,
    useable = false,
    description = 'SNS Pistol Mk2'
},
['weapon_heavypistol'] = {
    name = 'weapon_heavypistol',
    label = 'Heavy Pistol',
    weight = 1050,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_heavypistol.png',
    unique = true,
    useable = false,
    description = 'Heavy Pistol'
},
['weapon_vintagepistol'] = {
    name = 'weapon_vintagepistol',
    label = 'Vintage Pistol',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_vintagepistol.png',
    unique = true,
    useable = false,
    description = 'Vintage Pistol'
},
['weapon_marksmanpistol'] = {
    name = 'weapon_marksmanpistol',
    label = 'Marksman Pistol',
    weight = 1000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_marksmanpistol.png',
    unique = true,
    useable = false,
    description = 'Marksman Pistol'
},
['weapon_revolver'] = {
    name = 'weapon_revolver',
    label = 'Heavy Revolver',
    weight = 1100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_revolver.png',
    unique = true,
    useable = false,
    description = 'Heavy Revolver'
},
['weapon_revolver_mk2'] = {
    name = 'weapon_revolver_mk2',
    label = 'Heavy Revolver Mk2',
    weight = 1100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_revolver_mk2.png',
    unique = true,
    useable = false,
    description = 'Heavy Revolver Mk2'
},
['weapon_doubleaction'] = {
    name = 'weapon_doubleaction',
    label = 'Double Action Revolver',
    weight = 1000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_doubleaction.png',
    unique = true,
    useable = false,
    description = 'Double Action Revolver'
},
['weapon_ceramicpistol'] = {
    name = 'weapon_ceramicpistol',
    label = 'Ceramic Pistol',
    weight = 800,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_ceramicpistol.png',
    unique = true,
    useable = false,
    description = 'Ceramic Pistol'
},
['weapon_navyrevolver'] = {
    name = 'weapon_navyrevolver',
    label = 'Navy Revolver',
    weight = 1100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_navyrevolver.png',
    unique = true,
    useable = false,
    description = 'Navy Revolver'
},
['weapon_gadgetpistol'] = {
    name = 'weapon_gadgetpistol',
    label = 'Perico Pistol',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_gadgetpistol.png',
    unique = true,
    useable = false,
    description = 'Perico Pistol'
},
['weapon_stungun'] = {
    name = 'weapon_stungun',
    label = 'Stun Gun',
    weight = 600,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_stungun.png',
    unique = true,
    useable = false,
    description = 'Stun Gun'
},
['weapon_flaregun'] = {
    name = 'weapon_flaregun',
    label = 'Flare Gun',
    weight = 500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_flaregun.png',
    unique = true,
    useable = false,
    description = 'Flare Gun'
},
['weapon_pistolxm3'] = {
    name = 'weapon_pistolxm3',
    label = 'WM 29 Pistol',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_pistolxm3.png',
    unique = true,
    useable = false,
    description = 'WM 29 Pistol'
},
['weapon_machinepistol'] = {
    name = 'weapon_machinepistol',
    label = 'Machine Pistol',
    weight = 1100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_machinepistol.png',
    unique = true,
    useable = false,
    description = 'Machine Pistol'
},

-- SMGs
['weapon_microsmg'] = {
    name = 'weapon_microsmg',
    label = 'Micro SMG',
    weight = 1800,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_microsmg.png',
    unique = true,
    useable = false,
    description = 'Micro SMG'
},
['weapon_smg'] = {
    name = 'weapon_smg',
    label = 'SMG',
    weight = 3100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_smg.png',
    unique = true,
    useable = false,
    description = 'SMG'
},
['weapon_smg_mk2'] = {
    name = 'weapon_smg_mk2',
    label = 'SMG Mk2',
    weight = 3100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_smg_mk2.png',
    unique = true,
    useable = false,
    description = 'SMG Mk2'
},
['weapon_assaultsmg'] = {
    name = 'weapon_assaultsmg',
    label = 'Assault SMG',
    weight = 2900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_assaultsmg.png',
    unique = true,
    useable = false,
    description = 'Assault SMG'
},
['weapon_combatpdw'] = {
    name = 'weapon_combatpdw',
    label = 'Combat PDW',
    weight = 2700,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_combatpdw.png',
    unique = true,
    useable = false,
    description = 'Combat PDW'
},
['weapon_minismg'] = {
    name = 'weapon_minismg',
    label = 'Mini SMG',
    weight = 2300,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_minismg.png',
    unique = true,
    useable = false,
    description = 'Mini SMG'
},
['weapon_tecpistol'] = {
    name = 'weapon_tecpistol',
    label = 'Tactical SMG',
    weight = 2500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_tecpistol.png',
    unique = true,
    useable = false,
    description = 'Tactical SMG'
},
['weapon_gusenberg'] = {
    name = 'weapon_gusenberg',
    label = 'Gusenberg Sweeper',
    weight = 4300,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_gusenberg.png',
    unique = true,
    useable = false,
    description = 'Gusenberg Sweeper'
},
['weapon_raycarbine'] = {
    name = 'weapon_raycarbine',
    label = 'Unholy Hellbringer',
    weight = 3000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_raycarbine.png',
    unique = true,
    useable = false,
    description = 'Unholy Hellbringer'
},

-- Schrotflinten
['weapon_pumpshotgun'] = {
    name = 'weapon_pumpshotgun',
    label = 'Pump Shotgun',
    weight = 3400,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_pumpshotgun.png',
    unique = true,
    useable = false,
    description = 'Pump Shotgun'
},
['weapon_pumpshotgun_mk2'] = {
    name = 'weapon_pumpshotgun_mk2',
    label = 'Pump Shotgun Mk2',
    weight = 3400,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_pumpshotgun_mk2.png',
    unique = true,
    useable = false,
    description = 'Pump Shotgun Mk2'
},
['weapon_sawnoffshotgun'] = {
    name = 'weapon_sawnoffshotgun',
    label = 'Sawed-Off Shotgun',
    weight = 2700,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_sawnoffshotgun.png',
    unique = true,
    useable = false,
    description = 'Sawed-Off Shotgun'
},
['weapon_bullpupshotgun'] = {
    name = 'weapon_bullpupshotgun',
    label = 'Bullpup Shotgun',
    weight = 3100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_bullpupshotgun.png',
    unique = true,
    useable = false,
    description = 'Bullpup Shotgun'
},
['weapon_assaultshotgun'] = {
    name = 'weapon_assaultshotgun',
    label = 'Assault Shotgun',
    weight = 3500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_assaultshotgun.png',
    unique = true,
    useable = false,
    description = 'Assault Shotgun'
},
['weapon_musket'] = {
    name = 'weapon_musket',
    label = 'Musket',
    weight = 4500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_musket.png',
    unique = true,
    useable = false,
    description = 'Musket'
},
['weapon_heavyshotgun'] = {
    name = 'weapon_heavyshotgun',
    label = 'Heavy Shotgun',
    weight = 3600,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_heavyshotgun.png',
    unique = true,
    useable = false,
    description = 'Heavy Shotgun'
},
['weapon_dbshotgun'] = {
    name = 'weapon_dbshotgun',
    label = 'Double Barrel Shotgun',
    weight = 3000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_dbshotgun.png',
    unique = true,
    useable = false,
    description = 'Double Barrel Shotgun'
},
['weapon_autoshotgun'] = {
    name = 'weapon_autoshotgun',
    label = 'Sweeper Shotgun',
    weight = 3700,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_autoshotgun.png',
    unique = true,
    useable = false,
    description = 'Sweeper Shotgun'
},
['weapon_combatshotgun'] = {
    name = 'weapon_combatshotgun',
    label = 'Combat Shotgun',
    weight = 3900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_combatshotgun.png',
    unique = true,
    useable = false,
    description = 'Combat Shotgun'
},

-- Sturmgewehre
['weapon_assaultrifle'] = {
    name = 'weapon_assaultrifle',
    label = 'Assault Rifle',
    weight = 4500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_assaultrifle.png',
    unique = true,
    useable = false,
    description = 'Assault Rifle'
},
['weapon_assaultrifle_mk2'] = {
    name = 'weapon_assaultrifle_mk2',
    label = 'Assault Rifle Mk2',
    weight = 4500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_assaultrifle_mk2.png',
    unique = true,
    useable = false,
    description = 'Assault Rifle Mk2'
},
['weapon_carbinerifle'] = {
    name = 'weapon_carbinerifle',
    label = 'Carbine Rifle',
    weight = 3900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_carbinerifle.png',
    unique = true,
    useable = false,
    description = 'Carbine Rifle'
},
['weapon_carbinerifle_mk2'] = {
    name = 'weapon_carbinerifle_mk2',
    label = 'Carbine Rifle Mk2',
    weight = 3900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_carbinerifle_mk2.png',
    unique = true,
    useable = false,
    description = 'Carbine Rifle Mk2'
},
['weapon_advancedrifle'] = {
    name = 'weapon_advancedrifle',
    label = 'Advanced Rifle',
    weight = 4100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_advancedrifle.png',
    unique = true,
    useable = false,
    description = 'Advanced Rifle'
},
['weapon_specialcarbine'] = {
    name = 'weapon_specialcarbine',
    label = 'Special Carbine',
    weight = 3800,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_specialcarbine.png',
    unique = true,
    useable = false,
    description = 'Special Carbine'
},
['weapon_specialcarbine_mk2'] = {
    name = 'weapon_specialcarbine_mk2',
    label = 'Special Carbine Mk2',
    weight = 3800,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_specialcarbine_mk2.png',
    unique = true,
    useable = false,
    description = 'Special Carbine Mk2'
},
['weapon_bullpuprifle'] = {
    name = 'weapon_bullpuprifle',
    label = 'Bullpup Rifle',
    weight = 3700,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_bullpuprifle.png',
    unique = true,
    useable = false,
    description = 'Bullpup Rifle'
},
['weapon_bullpuprifle_mk2'] = {
    name = 'weapon_bullpuprifle_mk2',
    label = 'Bullpup Rifle Mk2',
    weight = 3700,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_bullpuprifle_mk2.png',
    unique = true,
    useable = false,
    description = 'Bullpup Rifle Mk2'
},
['weapon_compactrifle'] = {
    name = 'weapon_compactrifle',
    label = 'Compact Rifle',
    weight = 3600,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_compactrifle.png',
    unique = true,
    useable = false,
    description = 'Compact Rifle'
},
['weapon_militaryrifle'] = {
    name = 'weapon_militaryrifle',
    label = 'Military Rifle',
    weight = 4300,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_militaryrifle.png',
    unique = true,
    useable = false,
    description = 'Military Rifle'
},
['weapon_heavyrifle'] = {
    name = 'weapon_heavyrifle',
    label = 'Heavy Rifle',
    weight = 4200,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_heavyrifle.png',
    unique = true,
    useable = false,
    description = 'Heavy Rifle'
},
['weapon_tacticalrifle'] = {
    name = 'weapon_tacticalrifle',
    label = 'Service Carbine',
    weight = 4000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_tacticalrifle.png',
    unique = true,
    useable = false,
    description = 'Service Carbine'
},
['weapon_battlerifle'] = {
    name = 'weapon_battlerifle',
    label = 'Battle Rifle',
    weight = 4400,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_battlerifle.png',
    unique = true,
    useable = false,
    description = 'Battle Rifle'
},

-- Maschinengewehre
['weapon_mg'] = {
    name = 'weapon_mg',
    label = 'MG',
    weight = 9000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_mg.png',
    unique = true,
    useable = false,
    description = 'MG'
},
['weapon_combatmg'] = {
    name = 'weapon_combatmg',
    label = 'Combat MG',
    weight = 10000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_combatmg.png',
    unique = true,
    useable = false,
    description = 'Combat MG'
},
['weapon_combatmg_mk2'] = {
    name = 'weapon_combatmg_mk2',
    label = 'Combat MG Mk2',
    weight = 10000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_combatmg_mk2.png',
    unique = true,
    useable = false,
    description = 'Combat MG Mk2'
},
['weapon_gusenberg'] = {
    name = 'weapon_gusenberg',
    label = 'Gusenberg Sweeper',
    weight = 8000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_gusenberg.png',
    unique = true,
    useable = false,
    description = 'Gusenberg Sweeper'
},

-- Scharfschützengewehre
['weapon_sniperrifle'] = {
    name = 'weapon_sniperrifle',
    label = 'Sniper Rifle',
    weight = 5500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_sniperrifle.png',
    unique = true,
    useable = false,
    description = 'Sniper Rifle'
},
['weapon_heavysniper'] = {
    name = 'weapon_heavysniper',
    label = 'Heavy Sniper',
    weight = 7000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_heavysniper.png',
    unique = true,
    useable = false,
    description = 'Heavy Sniper'
},
['weapon_heavysniper_mk2'] = {
    name = 'weapon_heavysniper_mk2',
    label = 'Heavy Sniper Mk2',
    weight = 7000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_heavysniper_mk2.png',
    unique = true,
    useable = false,
    description = 'Heavy Sniper Mk2'
},
['weapon_marksmanrifle'] = {
    name = 'weapon_marksmanrifle',
    label = 'Marksman Rifle',
    weight = 4500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_marksmanrifle.png',
    unique = true,
    useable = false,
    description = 'Marksman Rifle'
},
['weapon_marksmanrifle_mk2'] = {
    name = 'weapon_marksmanrifle_mk2',
    label = 'Marksman Rifle Mk2',
    weight = 4500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_marksmanrifle_mk2.png',
    unique = true,
    useable = false,
    description = 'Marksman Rifle Mk2'
},
['weapon_precisionrifle'] = {
    name = 'weapon_precisionrifle',
    label = 'Precision Rifle',
    weight = 5000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_precisionrifle.png',
    unique = true,
    useable = false,
    description = 'Precision Rifle'
},

-- Schwere Waffen
['weapon_rpg'] = {
    name = 'weapon_rpg',
    label = 'RPG',
    weight = 5000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_rpg.png',
    unique = true,
    useable = false,
    description = 'RPG'
},
['weapon_grenadelauncher'] = {
    name = 'weapon_grenadelauncher',
    label = 'Grenade Launcher',
    weight = 6000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_grenadelauncher.png',
    unique = true,
    useable = false,
    description = 'Grenade Launcher'
},
['weapon_grenadelauncher_smoke'] = {
    name = 'weapon_grenadelauncher_smoke',
    label = 'Grenade Launcher Smoke',
    weight = 6000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_grenadelauncher_smoke.png',
    unique = true,
    useable = false,
    description = 'Grenade Launcher Smoke'
},
['weapon_minigun'] = {
    name = 'weapon_minigun',
    label = 'Minigun',
    weight = 38000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_minigun.png',
    unique = true,
    useable = false,
    description = 'Minigun'
},
['weapon_firework'] = {
    name = 'weapon_firework',
    label = 'Firework Launcher',
    weight = 4000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_firework.png',
    unique = true,
    useable = false,
    description = 'Firework Launcher'
},
['weapon_railgun'] = {
    name = 'weapon_railgun',
    label = 'Railgun',
    weight = 8000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_railgun.png',
    unique = true,
    useable = false,
    description = 'Railgun'
},
['weapon_hominglauncher'] = {
    name = 'weapon_hominglauncher',
    label = 'Homing Launcher',
    weight = 7000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_hominglauncher.png',
    unique = true,
    useable = false,
    description = 'Homing Launcher'
},
['weapon_compactlauncher'] = {
    name = 'weapon_compactlauncher',
    label = 'Compact Launcher',
    weight = 2500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_compactlauncher.png',
    unique = true,
    useable = false,
    description = 'Compact Launcher'
},
['weapon_rayminigun'] = {
    name = 'weapon_rayminigun',
    label = 'Widowmaker',
    weight = 12000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_rayminigun.png',
    unique = true,
    useable = false,
    description = 'Widowmaker'
},
['weapon_emplauncher'] = {
    name = 'weapon_emplauncher',
    label = 'Compact EMP Launcher',
    weight = 3000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_emplauncher.png',
    unique = true,
    useable = false,
    description = 'Compact EMP Launcher'
},

-- Wurfwaffen
['weapon_grenade'] = {
    name = 'weapon_grenade',
    label = 'Grenade',
    weight = 350,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_grenade.png',
    unique = true,
    useable = false,
    description = 'Grenade'
},
['weapon_bzgas'] = {
    name = 'weapon_bzgas',
    label = 'BZ Gas',
    weight = 350,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_bzgas.png',
    unique = true,
    useable = false,
    description = 'BZ Gas'
},
['weapon_molotov'] = {
    name = 'weapon_molotov',
    label = 'Molotov Cocktail',
    weight = 450,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_molotov.png',
    unique = true,
    useable = false,
    description = 'Molotov Cocktail'
},
['weapon_stickybomb'] = {
    name = 'weapon_stickybomb',
    label = 'Sticky Bomb',
    weight = 450,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_stickybomb.png',
    unique = true,
    useable = false,
    description = 'Sticky Bomb'
},
['weapon_proxmine'] = {
    name = 'weapon_proxmine',
    label = 'Proximity Mine',
    weight = 500,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_proxmine.png',
    unique = true,
    useable = false,
    description = 'Proximity Mine'
},
['weapon_snowball'] = {
    name = 'weapon_snowball',
    label = 'Snowball',
    weight = 50,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_snowball.png',
    unique = true,
    useable = false,
    description = 'Snowball'
},
['weapon_pipebomb'] = {
    name = 'weapon_pipebomb',
    label = 'Pipe Bomb',
    weight = 400,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_pipebomb.png',
    unique = true,
    useable = false,
    description = 'Pipe Bomb'
},
['weapon_ball'] = {
    name = 'weapon_ball',
    label = 'Ball',
    weight = 100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_ball.png',
    unique = true,
    useable = false,
    description = 'Ball'
},
['weapon_smokegrenade'] = {
    name = 'weapon_smokegrenade',
    label = 'Tear Gas',
    weight = 350,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_smokegrenade.png',
    unique = true,
    useable = false,
    description = 'Tear Gas'
},
['weapon_flare'] = {
    name = 'weapon_flare',
    label = 'Flare',
    weight = 100,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_flare.png',
    unique = true,
    useable = false,
    description = 'Flare'
},

-- Nahkampf
['weapon_knife'] = {
    name = 'weapon_knife',
    label = 'Knife',
    weight = 300,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_knife.png',
    unique = true,
    useable = false,
    description = 'Knife'
},
['weapon_nightstick'] = {
    name = 'weapon_nightstick',
    label = 'Nightstick',
    weight = 800,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_nightstick.png',
    unique = true,
    useable = false,
    description = 'Nightstick'
},
['weapon_hammer'] = {
    name = 'weapon_hammer',
    label = 'Hammer',
    weight = 800,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_hammer.png',
    unique = true,
    useable = false,
    description = 'Hammer'
},
['weapon_bat'] = {
    name = 'weapon_bat',
    label = 'Baseball Bat',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_bat.png',
    unique = true,
    useable = false,
    description = 'Baseball Bat'
},
['weapon_golfclub'] = {
    name = 'weapon_golfclub',
    label = 'Golf Club',
    weight = 800,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_golfclub.png',
    unique = true,
    useable = false,
    description = 'Golf Club'
},
['weapon_crowbar'] = {
    name = 'weapon_crowbar',
    label = 'Crowbar',
    weight = 1000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_crowbar.png',
    unique = true,
    useable = false,
    description = 'Crowbar'
},
['weapon_bottle'] = {
    name = 'weapon_bottle',
    label = 'Bottle',
    weight = 350,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_bottle.png',
    unique = true,
    useable = false,
    description = 'Bottle'
},
['weapon_dagger'] = {
    name = 'weapon_dagger',
    label = 'Antique Cavalry Dagger',
    weight = 350,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_dagger.png',
    unique = true,
    useable = false,
    description = 'Antique Cavalry Dagger'
},
['weapon_hatchet'] = {
    name = 'weapon_hatchet',
    label = 'Hatchet',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_hatchet.png',
    unique = true,
    useable = false,
    description = 'Hatchet'
},
['weapon_knuckle'] = {
    name = 'weapon_knuckle',
    label = 'Brass Knuckles',
    weight = 300,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_knuckle.png',
    unique = true,
    useable = false,
    description = 'Brass Knuckles'
},
['weapon_machete'] = {
    name = 'weapon_machete',
    label = 'Machete',
    weight = 1000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_machete.png',
    unique = true,
    useable = false,
    description = 'Machete'
},
['weapon_flashlight'] = {
    name = 'weapon_flashlight',
    label = 'Flashlight',
    weight = 400,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_flashlight.png',
    unique = true,
    useable = false,
    description = 'Flashlight'
},
['weapon_switchblade'] = {
    name = 'weapon_switchblade',
    label = 'Switchblade',
    weight = 300,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_switchblade.png',
    unique = true,
    useable = false,
    description = 'Switchblade'
},
['weapon_poolcue'] = {
    name = 'weapon_poolcue',
    label = 'Pool Cue',
    weight = 700,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_poolcue.png',
    unique = true,
    useable = false,
    description = 'Pool Cue'
},
['weapon_wrench'] = {
    name = 'weapon_wrench',
    label = 'Pipe Wrench',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_wrench.png',
    unique = true,
    useable = false,
    description = 'Pipe Wrench'
},
['weapon_battleaxe'] = {
    name = 'weapon_battleaxe',
    label = 'Battle Axe',
    weight = 1200,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_battleaxe.png',
    unique = true,
    useable = false,
    description = 'Battle Axe'
},
['weapon_stone_hatchet'] = {
    name = 'weapon_stone_hatchet',
    label = 'Stone Hatchet',
    weight = 900,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_stone_hatchet.png',
    unique = true,
    useable = false,
    description = 'Stone Hatchet'
},
['weapon_candycane'] = {
    name = 'weapon_candycane',
    label = 'Candy Cane',
    weight = 200,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_candycane.png',
    unique = true,
    useable = false,
    description = 'Candy Cane'
},
['weapon_unarmed'] = {
    name = 'weapon_unarmed',
    label = 'Fists',
    weight = 0,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_unarmed.png',
    unique = true,
    useable = false,
    description = 'Fists'
},

-- Spezial
['weapon_petrolcan'] = {
    name = 'weapon_petrolcan',
    label = 'Jerry Can',
    weight = 12000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_petrolcan.png',
    unique = true,
    useable = false,
    description = 'Jerry Can'
},
['weapon_hazardcan'] = {
    name = 'weapon_hazardcan',
    label = 'Hazard Can',
    weight = 12000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_hazardcan.png',
    unique = true,
    useable = false,
    description = 'Hazard Can'
},
['weapon_fireextinguisher'] = {
    name = 'weapon_fireextinguisher',
    label = 'Fire Extinguisher',
    weight = 8000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_fireextinguisher.png',
    unique = true,
    useable = false,
    description = 'Fire Extinguisher'
},
['weapon_parachute'] = {
    name = 'weapon_parachute',
    label = 'Parachute',
    weight = 8000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_parachute.png',
    unique = true,
    useable = false,
    description = 'Parachute'
},
['weapon_fertilizercan'] = {
    name = 'weapon_fertilizercan',
    label = 'Fertilizer Can',
    weight = 12000,
    type = 'weapon',
    ammotype = 'AMMO_PISTOL',
    image = 'weapon_fertilizercan.png',
    unique = true,
    useable = false,
    description = 'Fertilizer Can'
},

-- Items
['ammo_pistol'] = {
    name = 'ammo_pistol',
    label = 'Pistolen Munition',
    weight = 100,
    type = 'item',
    image = 'ammo_pistol.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Pistolen Munition'
},
['ammo_smg'] = {
    name = 'ammo_smg',
    label = 'SMG Munition',
    weight = 120,
    type = 'item',
    image = 'ammo_smg.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'SMG Munition'
},
['ammo_rifle'] = {
    name = 'ammo_rifle',
    label = 'Gewehr Munition',
    weight = 150,
    type = 'item',
    image = 'ammo_rifle.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Gewehr Munition'
},
['ammo_shotgun'] = {
    name = 'ammo_shotgun',
    label = 'Schrotflinte Munition',
    weight = 200,
    type = 'item',
    image = 'ammo_shotgun.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Schrotflinte Munition'
},
['ammo_sniper'] = {
    name = 'ammo_sniper',
    label = 'Scharfschützen Munition',
    weight = 250,
    type = 'item',
    image = 'ammo_sniper.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Scharfschützen Munition'
},
['ammo_mg'] = {
    name = 'ammo_mg',
    label = 'MG Munition',
    weight = 180,
    type = 'item',
    image = 'ammo_mg.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'MG Munition'
},
['ammo_rocket'] = {
    name = 'ammo_rocket',
    label = 'Raketen',
    weight = 5000,
    type = 'item',
    image = 'ammo_rocket.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Raketen'
},
['ammo_grenade'] = {
    name = 'ammo_grenade',
    label = 'Granaten',
    weight = 350,
    type = 'item',
    image = 'ammo_grenade.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Granaten'
},
['ammo_50cal'] = {
    name = 'ammo_50cal',
    label = '.50 Cal Munition',
    weight = 300,
    type = 'item',
    image = 'ammo_50cal.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = '.50 Cal Munition'
},
['ammo_armor_piercing'] = {
    name = 'ammo_armor_piercing',
    label = 'Panzerbrechende Munition',
    weight = 400,
    type = 'item',
    image = 'ammo_armor_piercing.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Panzerbrechende Munition'
},
['weapon_flashlight'] = {
    name = 'weapon_flashlight',
    label = 'Taschenlampe Aufsatz',
    weight = 50,
    type = 'item',
    image = 'weapon_flashlight.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Taschenlampe Aufsatz'
},
['weapon_scope'] = {
    name = 'weapon_scope',
    label = 'Zielfernrohr',
    weight = 200,
    type = 'item',
    image = 'weapon_scope.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Zielfernrohr'
},
['weapon_suppressor'] = {
    name = 'weapon_suppressor',
    label = 'Schalldämpfer',
    weight = 300,
    type = 'item',
    image = 'weapon_suppressor.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Schalldämpfer'
},
['weapon_grip'] = {
    name = 'weapon_grip',
    label = 'Griff',
    weight = 100,
    type = 'item',
    image = 'weapon_grip.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Griff'
},
['weapon_extendedmag'] = {
    name = 'weapon_extendedmag',
    label = 'Erweitertes Magazin',
    weight = 150,
    type = 'item',
    image = 'weapon_extendedmag.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Erweitertes Magazin'
},
['weapon_luxuryfinish'] = {
    name = 'weapon_luxuryfinish',
    label = 'Luxus Waffenskin',
    weight = 500,
    type = 'item',
    image = 'weapon_luxuryfinish.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Luxus Waffenskin'
},
['weapon_tacticalfinish'] = {
    name = 'weapon_tacticalfinish',
    label = 'Taktischer Waffenskin',
    weight = 400,
    type = 'item',
    image = 'weapon_tacticalfinish.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Taktischer Waffenskin'
},
['bandage'] = {
    name = 'bandage',
    label = 'Verband',
    weight = 115,
    type = 'item',
    image = 'bandage.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Verband'
},
['medkit'] = {
    name = 'medkit',
    label = 'Erste-Hilfe-Kasten',
    weight = 450,
    type = 'item',
    image = 'medkit.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Erste-Hilfe-Kasten'
},
['painkiller'] = {
    name = 'painkiller',
    label = 'Schmerzmittel',
    weight = 80,
    type = 'item',
    image = 'painkiller.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Schmerzmittel'
},
['adrenaline'] = {
    name = 'adrenaline',
    label = 'Adrenalin',
    weight = 200,
    type = 'item',
    image = 'adrenaline.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Adrenalin'
},
['water'] = {
    name = 'water',
    label = 'Wasser',
    weight = 500,
    type = 'item',
    image = 'water.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Wasser'
},
['bread'] = {
    name = 'bread',
    label = 'Brot',
    weight = 150,
    type = 'item',
    image = 'bread.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Brot'
},
['sandwich'] = {
    name = 'sandwich',
    label = 'Sandwich',
    weight = 200,
    type = 'item',
    image = 'sandwich.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Sandwich'
},
['burger'] = {
    name = 'burger',
    label = 'Burger',
    weight = 220,
    type = 'item',
    image = 'burger.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Burger'
},
['cola'] = {
    name = 'cola',
    label = 'Cola',
    weight = 350,
    type = 'item',
    image = 'cola.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Cola'
},
['coffee'] = {
    name = 'coffee',
    label = 'Kaffee',
    weight = 300,
    type = 'item',
    image = 'coffee.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Kaffee'
},
['phone'] = {
    name = 'phone',
    label = 'Telefon',
    weight = 190,
    type = 'item',
    image = 'phone.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Telefon'
},
['radio'] = {
    name = 'radio',
    label = 'Funkgerät',
    weight = 200,
    type = 'item',
    image = 'radio.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Funkgerät'
},
['lockpick'] = {
    name = 'lockpick',
    label = 'Dietrich',
    weight = 50,
    type = 'item',
    image = 'lockpick.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Dietrich'
},
['repairkit'] = {
    name = 'repairkit',
    label = 'Reparaturkit',
    weight = 2500,
    type = 'item',
    image = 'repairkit.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Reparaturkit'
},
['binoculars'] = {
    name = 'binoculars',
    label = 'Fernglas',
    weight = 400,
    type = 'item',
    image = 'binoculars.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Fernglas'
},
['flashlight'] = {
    name = 'flashlight',
    label = 'Taschenlampe',
    weight = 125,
    type = 'item',
    image = 'flashlight.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Taschenlampe'
},
['armor'] = {
    name = 'armor',
    label = 'Schutzweste',
    weight = 3000,
    type = 'item',
    image = 'armor.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Schutzweste'
},
['helmet'] = {
    name = 'helmet',
    label = 'Helm',
    weight = 1500,
    type = 'item',
    image = 'helmet.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Helm'
},
['gasmask'] = {
    name = 'gasmask',
    label = 'Gasmaske',
    weight = 800,
    type = 'item',
    image = 'gasmask.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Gasmaske'
},
['parachute'] = {
    name = 'parachute',
    label = 'Fallschirm',
    weight = 8000,
    type = 'item',
    image = 'parachute.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Fallschirm'
},
['jerrycan'] = {
    name = 'jerrycan',
    label = 'Benzinkanister',
    weight = 12000,
    type = 'item',
    image = 'jerrycan.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Benzinkanister'
},
['fireextinguisher'] = {
    name = 'fireextinguisher',
    label = 'Feuerlöscher',
    weight = 8000,
    type = 'item',
    image = 'fireextinguisher.png',
    unique = true,
    useable = true,
    shouldClose = true,
    description = 'Feuerlöscher'
},
['rope'] = {
    name = 'rope',
    label = 'Seil',
    weight = 500,
    type = 'item',
    image = 'rope.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Seil'
},
['handcuffs'] = {
    name = 'handcuffs',
    label = 'Handschellen',
    weight = 200,
    type = 'item',
    image = 'handcuffs.png',
    unique = false,
    useable = true,
    shouldClose = true,
    description = 'Handschellen'
},
